# Use a imagem base oficial do Node.js LTS
FROM node:19-alpine

# Instale o curl
RUN apk add --no-cache curl

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copie os arquivos package.json e package-lock.json para o diretório de trabalho
COPY package*.json .

# Instale as dependências da aplicação
RUN npm install

# Copie o restante dos arquivos da aplicação para o contêiner
COPY . .

# Construa o projeto Next.js para produção
RUN npm run build

# Exponha a porta na qual o Next.js irá rodar
EXPOSE 3000

# Comando para rodar a aplicação em modo de produção
CMD ["npm", "start"]
