services:
  db:
    image: postgres
    restart: always
    container_name: morena_db
    environment:
      POSTGRES_USER: "morena"
      POSTGRES_PASSWORD: "example"
      POSTGRES_DB: "mordatabasemorenaena"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: morena_web
    restart: always
    ports:
      - "3000:3000"

    command: "npm start"
    depends_on:
      - servidor

  servidor:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: morena_server
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db

volumes:
  postgres_data:
