FROM php:8.2-fpm

# Instalar dependências do sistema
RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    jpegoptim optipng pngquant gifsicle \
    vim \
    git \
    curl \
    zip \
    unzip \
    libpq-dev \
    libzip-dev \
    libexif-dev \
    libonig-dev

# Definir diretório de trabalho
WORKDIR /var/www

# Copiar arquivos do Composer
COPY composer.lock composer.json /var/www/

# Instalar dependências do PHP
RUN docker-php-ext-install pdo pdo_pgsql mbstring zip exif pcntl gd

# Instalar o Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Instalar as dependências do Composer
RUN composer install --prefer-dist --no-scripts --no-dev --optimize-autoloader

# Copiar o restante dos arquivos da aplicação
COPY . .

# Limpar o cache do apt
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Corrigindo a biblioteca 
# nunomaduro/collision

RUN composer dump-autoload \
    && php artisan key:generate \
    && php artisan config:cache \
    && php artisan jwt:secret

# Expor a porta para o Laravel
EXPOSE 8000

# Comando para iniciar o Laravel
CMD [ "php", "artisan", "serve", "--host=0.0.0.0", "--port=8000" ]